# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Log-Message
version:      0.02
version_from: lib/Catalyst/Plugin/Log/Message.pm
installdirs:  site
requires:
    Catalyst:                      5.66
    Log::Message:                  0.01
    Test::More:                    0.62

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
